
channels:
- conda-forge
dependencies:
- python=3.8.8
- pip:
  - azureml-defaults
  - tensorflow-gpu==2.5
  - matplotlib
  - pandas
  - tqdm
  - tensorflow_hub
  - tensorflow_text
  - tensorflow_addons
